const id=(x)=>x;
export const seed = () => ({ app:'NEXUS', schemaVersion:1, exportedAt:null, worldName:'Golden Axis — Sample World', baseCurrency:'USD', simulationDate:'2026-01-01', settings:{theme:'dark',grid:true,layout:'cose'}, entities:[
{id:id('founder'),name:'Founder',type:'Person',country:'India',jurisdiction:'India',status:'Active',createdAt:'2026-01-01',metadata:{openingBalance:100000}},
{id:id('trust'),name:'Family Trust',type:'Trust',country:'India',jurisdiction:'India',status:'Active',createdAt:'2026-01-01',metadata:{openingBalance:250000}},
{id:id('estonia'),name:'Estonian Tech OÜ',type:'Company',country:'Estonia',jurisdiction:'Estonia',status:'Active',createdAt:'2026-01-01',metadata:{openingBalance:80000}},
{id:id('india'),name:'Indian IT Services',type:'Company',country:'India',jurisdiction:'India',status:'Active',createdAt:'2026-01-01',metadata:{openingBalance:120000}},
{id:id('section8'),name:'Section 8 Research',type:'Section8',country:'India',jurisdiction:'India',status:'Active',createdAt:'2026-01-01',metadata:{openingBalance:15000}},
{id:id('steel'),name:'Steel Business',type:'Business',country:'India',jurisdiction:'India',status:'Active',createdAt:'2026-01-01',metadata:{openingBalance:180000}},
{id:id('scrap'),name:'Scrap Business',type:'Business',country:'India',jurisdiction:'India',status:'Active',createdAt:'2026-01-01',metadata:{openingBalance:45000}}
],relationships:[
{id:'r1',sourceEntityId:'founder',targetEntityId:'estonia',type:'OWNS',percentage:100,startDate:'2026-01-01',description:'Illustrative sample ownership'},
{id:'r2',sourceEntityId:'founder',targetEntityId:'trust',type:'CONTROLS',percentage:0,startDate:'2026-01-01',description:'Illustrative sample governance'},
{id:'r3',sourceEntityId:'trust',targetEntityId:'india',type:'OWNS',percentage:100,startDate:'2026-01-01',description:'Illustrative sample ownership'},
{id:'r4',sourceEntityId:'trust',targetEntityId:'steel',type:'OWNS',percentage:100,startDate:'2026-01-01',description:'Illustrative sample ownership'},
{id:'r5',sourceEntityId:'trust',targetEntityId:'scrap',type:'OWNS',percentage:100,startDate:'2026-01-01',description:'Illustrative sample ownership'},
{id:'r6',sourceEntityId:'india',targetEntityId:'estonia',type:'PROVIDES_SERVICES_TO',percentage:0,startDate:'2026-01-01',description:'Configured commercial relationship'}
],financialFlows:[{id:'f1',sourceEntityId:'estonia',destinationEntityId:'india',amount:8000,currency:'USD',frequency:'Monthly',startDate:'2026-01-01',endDate:'',description:'Illustrative development service fee',category:'Services',status:'Active'}],revenues:[{id:'rev1',entityId:'estonia',name:'International software revenue',amount:22000,currency:'USD',frequency:'Monthly',startDate:'2026-01-01',endDate:'',description:'Illustrative sample revenue',status:'Active'}],expenses:[{id:'exp1',entityId:'india',name:'Operating expenses',amount:3500,currency:'USD',frequency:'Monthly',startDate:'2026-01-01',endDate:'',description:'Illustrative sample expense',status:'Active'}],assets:[{id:'a1',ownerEntityId:'trust',name:'Example Property',type:'Property',purchaseValue:300000,currentValue:340000,currency:'USD',purchaseDate:'2026-01-01',income:1200,recurringExpenses:250,status:'Active',description:'Illustrative sample asset'}],employees:[{id:'e1',entityId:'india',name:'Sample Engineer',role:'Engineer',department:'Delivery',salary:2200,currency:'USD',joiningDate:'2026-01-01',leavingDate:'',status:'Active'}],investments:[{id:'i1',investorEntityId:'trust',targetEntityId:'section8',amount:10000,currency:'USD',ownershipPercentage:0,investmentDate:'2026-01-01',status:'Active',description:'Illustrative capital support'}],contracts:[{id:'c1',partyA:'estonia',partyB:'india',type:'Software Development Agreement',description:'Illustrative configured agreement',startDate:'2026-01-01',endDate:'',recurringAmount:8000,currency:'USD',frequency:'Monthly',status:'Active'}],events:[] });
